### ISSUE TITLE
aarch64 Linux?

### ISSUE THREAD

**Issue by johnnynunez** [LuisaGroup/LuisaCompute#164]
I've get error

![Image](https://github.com/user-attachments/assets/0115cb53-991e-468c-823b-d1194b7f0fce)

![Image](https://github.com/user-attachments/assets/f5bf57c9-ee83-4b01-b434-a33eef4d6e36)

**Comment by Mike-Leo-Smith** [comment]
Hi, @johnnynunez 

I have fixed this issue recently in c5fe2335 (sorry it's mixed with other changes). Could you try `git pull` and `git submodule update --recursive --init` in your local LuisaRender repo?

Or, if you are using a fork and can not conveniently track the changes, you can directly edit `platform.cpp`, by commenting out this `#include <sys/sysctl.h>` and change the implementation of `luisa::string cpu_name()` to return an empty/default string.

**Comment by johnnynunez** [comment]
> Hi, [@johnnynunez](https://github.com/johnnynunez)
> 
> I have fixed this issue recently in [c5fe233](https://github.com/LuisaGroup/LuisaCompute/commit/c5fe23358ecf5bb76051fb7b1a9a9238e0e2ef64) (sorry it's mixed with other changes). Could you try `git pull` and `git submodule update --recursive --init` in your local LuisaRender repo?
> 
> Or, if you are using a fork and can not conveniently track the changes, you can directly edit `platform.cpp`, by commenting out this `#include <sys/sysctl.h>` and change the implementation of `luisa::string cpu_name()` to return an empty/default string.

Thanks Mike.
Also I’m working on for arm runners here with vulkan and cuda arm.

**Comment by johnnynunez** [comment]
@Mike-Leo-Smith still appear some errors
You can see it here https://github.com/LuisaGroup/LuisaCompute/pull/166

**Comment by Mike-Leo-Smith** [comment]
> [@Mike-Leo-Smith](https://github.com/Mike-Leo-Smith) still appear some errors You can see it here [#165](https://github.com/LuisaGroup/LuisaCompute/pull/165)

Thanks for the testing! The fix hasn't been merged into the main `stable` branch. You would need to use the `next` branch.

**Comment by johnnynunez** [comment]
> > [@Mike-Leo-Smith](https://github.com/Mike-Leo-Smith) still appear some errors You can see it here [#165](https://github.com/LuisaGroup/LuisaCompute/pull/165)
> 
> Thanks for the testing! The fix hasn't been merged into the main `stable` branch. You would need to use the `next` branch.

in next it's working. Thins include vulkan sdk arm and cuda 12.8 sbsa (gh200)

![Image](https://github.com/user-attachments/assets/fe880165-cb25-4420-9f45-638b39930718)

**Comment by johnnynunez** [comment]
from my side all is done @Mike-Leo-Smith thank you for your repos

**Comment by Mike-Leo-Smith** [comment]
> from my side all is done [@Mike-Leo-Smith](https://github.com/Mike-Leo-Smith) thank you for your repos

I have merged the PR. Thank you for contributing!

**Comment by johnnynunez** [comment]
@Mike-Leo-Smith thank you to! I want this ready for DIGITS https://www.nvidia.com/en-us/project-digits/ <3

FYI: I did the same PR for LuisaRender
